language: node_js
node_js:
  - "0.12"
services:
  - mongodb
before_script:
  - sleep 15
script:
  - node server/server.js &
  - npm test

after_script:
  - sleep 15
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec ./test/test.js
  - cat ./coverage/lcov.info | ./bin/coveralls.js --verbose
